# Generated by Django 4.2.6 on 2023-10-05 21:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+12125552368",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
